apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-test-2-config
  namespace: default
data:
  default.conf: |
    server {
        listen       80 default_server;
        server_name  _;

        default_type text/plain;

        location / {
            return 200 'I am 1.27\n';
        }
    }
