apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: longhorn-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
